server:
  port: 8081
spring:
  application:
    name: package-delivery-consumer
  datasource:
    url: jdbc:mysql://localhost:3306/tracking
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    addresses: ${RABBIT_URI}

rabbitmq:
  queue: package_delivery_queue